version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.raspberry
    container_name: dua-connect-frontend
    ports:
      - "8091:8091"
    env_file:
      - .env
    depends_on:
      - pocketbase
    networks:
      - app-network
    restart: unless-stopped

  pocketbase:
    build:
      context: ./pb
      dockerfile: Dockerfile.raspberry
    container_name: dua-connect-pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
