version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dua-connect-frontend
    ports:
      - "8091:8091"
    env_file:
      - .env
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./pb
      dockerfile: Dockerfile
    container_name: dua-connect-pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pb/pb_data:/pb/pb_data
