FROM alpine:latest

RUN apk add --no-cache \
    unzip \
    ca-certificates

# Download ARM64 version of PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v0.27.2/pocketbase_0.27.2_linux_arm64.zip /tmp/pb.zip

RUN unzip /tmp/pb.zip -d /pb/

WORKDIR /pb

EXPOSE 8090

CMD ["./pocketbase", "serve", "--http=0.0.0.0:8090"] 